server:
  port: 0

spring:
  jackson:
    serialization:
      fail-on-empty-beans: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6433/explore-main
    username: explore-main
    password: explore-main

logging:
  level:
    "org.springframework.orm.jpa": INFO
    "org.springframework.transaction": INFO
    "org.springframework.transaction.interceptor": TRACE
    "org.springframework.orm.jpa.JpaTransactionManager": DEBUG
    "org.hibernate.SQL": DEBUG
    "org.hibernate.orm.jdbc.bind": trace

discovery:
  services:
    stats-server-id: stats-server