services:
  stats-db:
    image: postgres:16.1
    container_name: explore-postgres-stats
    ports:
      - "6432:5432"
    networks:
      - ewm-net
    environment:
      - POSTGRES_PASSWORD=explore-stats
      - POSTGRES_USER=explore-stats
      - POSTGRES_DB=explore-stats
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  main-db:
    image: postgres:16.1
    container_name: explore-postgres-main
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "6433:5432"
    networks:
      - ewm-net
    environment:
      - POSTGRES_PASSWORD=explore-main
      - POSTGRES_USER=explore-main
      - POSTGRES_DB=explore-main
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  discovery-server:
    build: infra/discovery-server
    image: discovery-server
    container_name: discovery-server
    networks:
      - ewm-net
    ports:
      - "8761:8761"
    healthcheck:
      test: "curl --fail --silent discovery-server:8761/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 10s
      retries: 10

  config-server:
    build: infra/config-server
    image: config-server
    container_name: config-server
    networks:
      - ewm-net
    depends_on:
      discovery-server:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-server:8761/eureka
    healthcheck:
      test: >
        sh -c '
          PORT_APP=$$(curl -s -H "Accept: application/json" --fail http://discovery-server:8761/eureka/apps/config-server |
            jq -r ".application.instance[0].port[\"$$\"]");
          echo "Discovered PORT_APP=$$PORT_APP";
          if [ -n "$$PORT_APP" ]; then
            curl -sf http://config-server:$$PORT_APP/actuator/health || exit 1
          else
            exit 1
          fi
        '
      interval: 30s
      timeout: 10s
      retries: 3

  gateway-server:
    build: infra/gateway-server
    image: gateway-server
    container_name: gateway-server
    networks:
      - ewm-net
    ports:
      - "8080:8080"
    depends_on:
      config-server:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-server:8761/eureka
    healthcheck:
      test: >
        sh -c '
          PORT_APP=$$(curl -s -H "Accept: application/json" --fail http://discovery-server:8761/eureka/apps/gateway-server |
            jq -r ".application.instance[0].port[\"$$\"]");
          echo "Discovered PORT_APP=$$PORT_APP";
          if [ -n "$$PORT_APP" ]; then
            curl -sf http://gateway-server:$$PORT_APP/actuator/health || exit 1
          else
            exit 1
          fi
        '
      interval: 20s
      timeout: 5s
      retries: 10

  stats-server:
    build: stats/stats-server
    image: stats-server
    container_name: stats-server
    networks:
      - ewm-net
    depends_on:
      stats-db:
        condition: service_healthy
      config-server:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-server:8761/eureka
      - DB_URL=jdbc:postgresql://stats-db:5432/explore-stats
    healthcheck:
      test: >
        sh -c '
          PORT_APP=$$(curl -s -H "Accept: application/json" --fail http://discovery-server:8761/eureka/apps/stats-server |
            jq -r ".application.instance[0].port[\"$$\"]");
          echo "Discovered PORT_APP=$$PORT_APP";
          if [ -n "$$PORT_APP" ]; then
            curl -sf http://stats-server:$$PORT_APP/actuator/health || exit 1
          else
            exit 1
          fi
        '
      timeout: 5s
      interval: 25s
      retries: 10

  ewm-event:
    build: core/event-service
    image: event-service
    container_name: ewm-event
    networks:
      - ewm-net
    depends_on:
      main-db:
        condition: service_healthy
      config-server:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-server:8761/eureka
      - DB_URL=jdbc:postgresql://main-db:5432/ewm_event
    healthcheck:
      test: >
        sh -c '
          PORT_APP=$$(curl -s -H "Accept: application/json" --fail http://discovery-server:8761/eureka/apps/event-service |
            jq -r ".application.instance[0].port[\"$$\"]");
          echo "Discovered PORT_APP=$$PORT_APP";
          if [ -n "$$PORT_APP" ]; then
            curl -sf http://event-service:$$PORT_APP/actuator/health || exit 1
          else
            exit 1
          fi
        '
      timeout: 5s
      interval: 25s
      retries: 10

  ewm-user:
    build: core/user-service
    image: user-service
    container_name: ewm-user
    networks:
      - ewm-net
    depends_on:
      main-db:
        condition: service_healthy
      config-server:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-server:8761/eureka
      - DB_URL=jdbc:postgresql://main-db:5432/ewm_user
    healthcheck:
      test: >
        sh -c '
          PORT_APP=$$(curl -s -H "Accept: application/json" --fail http://discovery-server:8761/eureka/apps/user-service |
            jq -r ".application.instance[0].port[\"$$\"]");
          echo "Discovered PORT_APP=$$PORT_APP";
          if [ -n "$$PORT_APP" ]; then
            curl -sf http://user-service:$$PORT_APP/actuator/health || exit 1
          else
            exit 1
          fi
        '
      timeout: 5s
      interval: 25s
      retries: 10

  ewm-comment:
    build: core/comment-service
    image: comment-service
    container_name: ewm-comment
    networks:
      - ewm-net
    depends_on:
      main-db:
        condition: service_healthy
      config-server:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-server:8761/eureka
      - DB_URL=jdbc:postgresql://main-db:5432/ewm_comment
    healthcheck:
      test: >
        sh -c '
          PORT_APP=$$(curl -s -H "Accept: application/json" --fail http://discovery-server:8761/eureka/apps/comment-service |
            jq -r ".application.instance[0].port[\"$$\"]");
          echo "Discovered PORT_APP=$$PORT_APP";
          if [ -n "$$PORT_APP" ]; then
            curl -sf http://comment-service:$$PORT_APP/actuator/health || exit 1
          else
            exit 1
          fi
        '
      timeout: 5s
      interval: 25s
      retries: 10

  ewm-location:
    build: core/location-service
    image: location-service
    container_name: ewm-location
    networks:
      - ewm-net
    depends_on:
      main-db:
        condition: service_healthy
      config-server:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-server:8761/eureka
      - DB_URL=jdbc:postgresql://main-db:5432/ewm_location
    healthcheck:
      test: >
        sh -c '
          PORT_APP=$$(curl -s -H "Accept: application/json" --fail http://discovery-server:8761/eureka/apps/location-service |
            jq -r ".application.instance[0].port[\"$$\"]");
          echo "Discovered PORT_APP=$$PORT_APP";
          if [ -n "$$PORT_APP" ]; then
            curl -sf http://location-service:$$PORT_APP/actuator/health || exit 1
          else
            exit 1
          fi
        '
      timeout: 5s
      interval: 25s
      retries: 10

  ewm-request:
    build: core/request-service
    image: request-service
    container_name: ewm-request
    networks:
      - ewm-net
    depends_on:
      main-db:
        condition: service_healthy
      config-server:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-server:8761/eureka
      - DB_URL=jdbc:postgresql://main-db:5432/ewm_request
    healthcheck:
      test: >
        sh -c '
          PORT_APP=$$(curl -s -H "Accept: application/json" --fail http://discovery-server:8761/eureka/apps/request-service |
            jq -r ".application.instance[0].port[\"$$\"]");
          echo "Discovered PORT_APP=$$PORT_APP";
          if [ -n "$$PORT_APP" ]; then
            curl -sf http://request-service:$$PORT_APP/actuator/health || exit 1
          else
            exit 1
          fi
        '
      timeout: 5s
      interval: 25s
      retries: 10

  kafka:
    image: confluentinc/confluent-local:7.4.3
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092" # for client connections
      - "9101:9101" # JMX
    restart: unless-stopped
    networks:
      - ewm-net
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      CLUSTER_ID: 'K0EA9p0yEe6MkAAAAkKsEg'

  kafka-init-topics:
    image: confluentinc/confluent-local:7.4.3
    container_name: kafka-init-topics
    depends_on:
      - kafka
    networks:
      - ewm-net
    command: "bash -c \
        'kafka-topics --create --topic stats.user-actions.v1 \
                     --partitions 1 --replication-factor 1 --if-not-exists \
                     --bootstrap-server kafka:29092 && \
        kafka-topics --create --topic stats.events-similarity.v1 \
                     --partitions 1 --replication-factor 1 --if-not-exists \
                     --bootstrap-server kafka:29092'
      "
    init: true

  collector:
    build: stats/collector
    container_name: ewm-stats-collector
    depends_on:
      config-server:
        condition: service_healthy
    networks:
      - ewm-net
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SERVER_PORT=8085
    healthcheck:
      test: "curl --fail --silent localhost:8085/actuator/health | grep UP || exit 1"
      timeout: 5s
      interval: 25s
      retries: 10

  aggregator:
    build: stats/aggregator
    container_name: ewm-stats-aggregator
    depends_on:
      config-server:
        condition: service_healthy
    networks:
      - ewm-net
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SERVER_PORT=8086
    healthcheck:
      test: "curl --fail --silent localhost:8086/actuator/health | grep UP || exit 1"
      timeout: 5s
      interval: 25s
      retries: 10

  analyzer:
    build: stats/analyzer
    container_name: ewm-stats-analyzer
    depends_on:
      stats-db:
        condition: service_healthy
      config-server:
        condition: service_healthy
    networks:
      - ewm-net
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/explore-stats
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SERVER_PORT=8087
    healthcheck:
      test: "curl --fail --silent localhost:8087/actuator/health | grep UP || exit 1"
      timeout: 5s
      interval: 25s
      retries: 10

networks:
  ewm-net: