grpc:
  server:
    port: 0
  client:
    collector:
      address: 'discovery:///collector'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

collector:
  kafka:
    bootstrap-servers: ${KAFKA_URL:localhost:9092}
    client-id-config: "producer-1"
    producer-key-serializer: "org.apache.kafka.common.serialization.StringSerializer"
    producer-value-serializer: "ru.yandex.practicum.serializer.AvroSerializer"
    user-action-topic: "stats.user-actions.v1"