syntax = "proto3";

option java_multiple_files = true;
option java_package = "ru.yandex.practicum.grpc.stats.analyzer";
import "stats/massages/recommendation_request.proto";

service RecommendationsController{
  rpc GetRecommendationsForUser(stats.messages.request.UserPredictionsRequestProto)
      returns (stream stats.messages.request.RecommendedEventProto);

  rpc GetSimilarEvents(stats.messages.request.SimilarEventsRequestProto)
      returns (stream stats.messages.request.RecommendedEventProto);

  rpc GetInteractionsCount(stats.messages.request.InteractionsCountRequestProto)
      returns (stream stats.messages.request.RecommendedEventProto);
}